services:
  - type: web
    name: attendance-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn attendance_system.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        value: 8ji^tz&ztfie&24=955n(-reoqnpv1v9jweafa5x86qu#0l6*_

      - key: DEBUG
        value: False
static:
  - name: static
    path: /static
    dir: staticfiles
