# Generated by Django 5.2 on 2025-04-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_staff_staff_id_alter_staff_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.year')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.staff')),
            ],
            options={
                'unique_together': {('staff', 'assigned_class')},
            },
        ),
    ]
