# Generated by Django 5.2 on 2025-04-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_classroom_year_delete_attendance_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='section',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='a', max_length=30),
        ),
    ]
