# Generated by Django 5.2 on 2025-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_staffassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AddField(
            model_name='staff',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
