# Generated by Django 5.2 on 2025-04-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_staff_id_staff_s_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.year')),
            ],
        ),
    ]
