# Generated by Django 5.2 on 2025-04-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_classroom_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='year',
            constraint=models.UniqueConstraint(fields=('cname', 'year', 'section'), name='unique_class_year_section'),
        ),
    ]
